### ISSUE TITLE
compatible with any pcomplete buffer

### ISSUE THREAD

**Issue by CeleritasCelery** [Ambrevar/emacs-fish-completion#1]
I see that this package was design for `eshell`, however in recent version of emacs, `shell` also supports pcomplete. Will this package work with `shell`?

**Comment by Ambrevar** [comment]
Fixed in ed1534500addd407e9a65a19ee4788e2cf50f38f.
I'm not a big `shell` user so there might be some issues with the current implementation.
Let me know if everything works alright for you.

**Comment by CeleritasCelery** [comment]
works like a charm. Thank you.
